site_name: Apuntes de informática
site_url: https://mmourazos.github.io/Curso-2024-2025
repo_url: https://github.com/mmourazos/Curso-2024-2025

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
# nav:
#   - Inicio: index.md
#   - Apuntes 2024 - 2025: apuntes.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmourazos/Curso-2024-2025

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
