site_name: Apuntes de informática
site_url: https://mmourazos.github.io/Curso-2024-2025
repo_url: https://github.com/mmourazos/Curso-2024-2025

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - Home: index.md
  - Apuntes 2024 - 2025: apuntes.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmourazos/Curso-2024-2025
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
