DROP DATABASE IF EXISTS TalleresFaber;

CREATE DATABASE TalleresFaber;

USE TalleresFaber;

CREATE TABLE CLIENTES (
CodCliente VARCHAR(5) NOT NULL,
DNI VARCHAR(10) NOT NULL,
Apellidos VARCHAR(50),
Nombre VARCHAR(25),
Direccion VARCHAR(50),
Telefono VARCHAR(9),
PRIMARY KEY (CodCliente)
)ENGINE=InnoDB;

CREATE TABLE FACTURAS (
IdFactura INTEGER(4) NOT NULL,
FechaFactura DATE NOT NULL,
CodCliente VARCHAR(5) NOT NULL,
IdReparacion INTEGER,
PRIMARY KEY (IdFactura)
)ENGINE=InnoDB;

CREATE TABLE VEHICULOS (
Matricula VARCHAR(8) NOT NULL,
Marca VARCHAR(25),
Modelo VARCHAR(50),
Color VARCHAR(25),
FechaMatriculacion DATE,
CodCliente  VARCHAR(5),
PRIMARY KEY(Matricula)
)ENGINE=InnoDB;

CREATE TABLE REPARACIONES (
IdReparacion INTEGER NOT NULL AUTO_INCREMENT,
Matricula VARCHAR(8) NOT NULL,
FechaEntrada DATE,
Km DECIMAL(8,2),
Avería VARCHAR(200),
FechaSalida DATE,
Reparado  TINYINT(1),
Observaciones VARCHAR(250),
PRIMARY KEY(IdReparacion)
)ENGINE=InnoDB;

CREATE TABLE Intervienen (
CodEmpleado VARCHAR(5),
IdReparacion INTEGER NOT NULL,
Horas DECIMAL(4,2),
PRIMARY KEY(CodEmpleado, IdReparacion)
)ENGINE=InnoDB;

CREATE TABLE EMPLEADOS (
CodEmpleado VARCHAR(5) NOT NULL,
DNI VARCHAR(10) NOT NULL,
Nombre VARCHAR(25),
Apellidos VARCHAR(50),
Dirección VARCHAR(50),
Telefono VARCHAR(9),
CP VARCHAR(5),
FechaAlta DATE,
Categoria VARCHAR(50),
PRIMARY KEY(CodEmpleado)
)ENGINE=InnoDB;

CREATE TABLE Incluyen (
IdRecambio VARCHAR(10) NOT NULL,
IdReparacion INTEGER NOT NULL,
Unidades SMALLINT,
PRIMARY KEY (IdRecambio, IdReparacion)
)ENGINE=InnoDB;

CREATE TABLE RECAMBIOS (
IdRecambio VARCHAR(10) NOT NULL,
Descripcion VARCHAR(100),
UnidadBase VARCHAR(50),
Stock SMALLINT, 
PrecioReferencia DECIMAL(6,2),
PRIMARY KEY(IdRecambio)
)ENGINE=InnoDB;

CREATE TABLE Realizan (
IdReparacion INTEGER NOT NULL,
Referencia VARCHAR(10) NOT NULL,
Horas DECIMAL(4,2),
PRIMARY KEY(IdReparacion, Referencia)
)ENGINE=InnoDB;

CREATE TABLE ACTUACIONES (
Referencia VARCHAR(10) NOT NULL,
Descripcion VARCHAR(100),
TiempoEstimado DECIMAL(4,2),
Importe DECIMAL(6,2),
PRIMARY KEY(Referencia)
)ENGINE=InnoDB;

ALTER TABLE FACTURAS
ADD CONSTRAINT FACT_FK_CodCli FOREIGN KEY(CodCliente )REFERENCES CLIENTES(CodCliente) 
ON DELETE RESTRICT ON UPDATE CASCADE,
ADD CONSTRAINT FACT_FK_IdRep FOREIGN KEY(IdReparacion )REFERENCES REPARACIONES(IdReparacion)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE VEHICULOS
ADD CONSTRAINT VEHIC_FK_CodCli FOREIGN KEY(CodCliente )REFERENCES CLIENTES(CodCliente)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE REPARACIONES
ADD CONSTRAINT REPAR_FK_CodRep FOREIGN KEY(Matricula )REFERENCES VEHICULOS(Matricula)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Intervienen
ADD CONSTRAINT Inter_FK_CodEm FOREIGN KEY(CodEmpleado) REFERENCES EMPLEADOS(CodEmpleado)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT Inter_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Incluyen
ADD CONSTRAINT Incluy_FK_IdRec FOREIGN KEY(IdRecambio) REFERENCES RECAMBIOS(IdRecambio)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT Incluy_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Realizan
ADD CONSTRAINT Real_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT Real_FK_Refer FOREIGN KEY(Referencia) REFERENCES ACTUACIONES(Referencia)
ON DELETE CASCADE ON UPDATE CASCADE;
